# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'untitled.ui'
#
# Created by: PyQt5 UI code generator 5.15.9
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtWidgets
from Terminal import CommandTerminal
from PyQt5.QtWidgets import QComboBox, QListView, QToolTip
from PyQt5.QtCore import Qt

# 自定义 QListView 类
class CustomListView(QListView):
    def mouseMoveEvent(self, event):
        index = self.indexAt(event.pos())
        if index.isValid():
            text = index.data()
            QToolTip.showText(event.globalPos(), text)
        else:
            QToolTip.hideText()
        super().mouseMoveEvent(event)

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(920, 755)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")

        self.tabWidget = QtWidgets.QTabWidget(self.centralwidget)
        self.tabWidget.setGeometry(QtCore.QRect(0, 0, 920, 631))
        self.tabWidget.setObjectName("tabWidget")
        self.tab = QtWidgets.QWidget()
        self.tab.setObjectName("tab")
        # self.horizontalLayoutWidget = QtWidgets.QWidget(self.tab)
        self.horizontalLayoutWidget_2 = QtWidgets.QWidget(self.tab)
        self.horizontalLayoutWidget_2.setGeometry(QtCore.QRect(0, 0, 891, 561))
        self.horizontalLayoutWidget_2.setObjectName("horizontalLayoutWidget_2")
        # self.horizontalLayoutWidget_1 = QtWidgets.QWidget(self.centralwidget)
        # self.horizontalLayoutWidget_1.setGeometry(QtCore.QRect(0, 0, 891, 561))
        # self.horizontalLayoutWidget_1.setObjectName("horizontalLayoutWidget_1")
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout(self.horizontalLayoutWidget_2)
        self.horizontalLayout_2.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")


        self.verticalLayout = QtWidgets.QVBoxLayout()
        self.verticalLayout.setObjectName("verticalLayout")
        
        self.comboBox_2 = QtWidgets.QComboBox(self.horizontalLayoutWidget_2)
        self.comboBox_2.setMinimumSize(QtCore.QSize(200, 0))
        self.comboBox_2.setObjectName("comboBox_2")
        self.verticalLayout.addWidget(self.comboBox_2)
        
        # spacerItem = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        # self.verticalLayout.addItem(spacerItem)
        self.listWidget = QtWidgets.QListWidget(self.horizontalLayoutWidget_2)
        self.listWidget.setObjectName("listWidget")
        item = QtWidgets.QListWidgetItem()
        self.listWidget.addItem(item)
        item = QtWidgets.QListWidgetItem()
        self.listWidget.addItem(item)
        item = QtWidgets.QListWidgetItem()
        self.listWidget.addItem(item)
        item = QtWidgets.QListWidgetItem()
        self.listWidget.addItem(item)
        item = QtWidgets.QListWidgetItem()
        self.listWidget.addItem(item)
        item = QtWidgets.QListWidgetItem()
        self.listWidget.addItem(item)
        self.verticalLayout.addWidget(self.listWidget)
        self.horizontalLayout_2.addLayout(self.verticalLayout)
        self.verticalLayout_3 = QtWidgets.QVBoxLayout()
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.horizontalLayout_5 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_5.setObjectName("horizontalLayout_5")
        # 创建一个水平方向的 QSplitter
        splitter = QtWidgets.QSplitter(QtCore.Qt.Horizontal)

        self.label_6 = QtWidgets.QLabel(self.horizontalLayoutWidget_2)
        self.label_6.setObjectName("label_6")
        # 将标签添加到 splitter
        splitter.addWidget(self.label_6)

        self.lineEdit_4 = QtWidgets.QLineEdit(self.horizontalLayoutWidget_2)
        self.lineEdit_4.setObjectName("lineEdit_4")
        # 将文本框添加到 splitter
        splitter.addWidget(self.lineEdit_4)

        # 设置伸缩因子，label_6 索引为 0，不伸缩；lineEdit_4 索引为 1，可伸缩
        splitter.setStretchFactor(0, 0)
        splitter.setStretchFactor(1, 1)

        self.pushButton_2 = QtWidgets.QPushButton(self.horizontalLayoutWidget_2)
        self.pushButton_2.setObjectName("pushButton_2")
        # 将按钮添加到 splitter
        splitter.addWidget(self.pushButton_2)

        self.pushButton_3 = QtWidgets.QPushButton(self.horizontalLayoutWidget_2)
        self.pushButton_3.setObjectName("pushButton_3")
        # 将按钮添加到 splitter
        splitter.addWidget(self.pushButton_3)

        # 将 splitter 添加到 horizontalLayout_5
        self.horizontalLayout_5.addWidget(splitter)

        self.verticalLayout_3.addLayout(self.horizontalLayout_5)
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.splitter = QtWidgets.QSplitter(self.horizontalLayoutWidget_2)
        self.splitter.setOrientation(QtCore.Qt.Horizontal)
        self.splitter.setObjectName("splitter")
        self.label_5 = QtWidgets.QLabel(self.splitter)
        self.label_5.setObjectName("label_5")
        # 将 label_5 添加到 splitter
        self.splitter.addWidget(self.label_5)

        # 设置伸缩因子，label_5 索引为 0，不伸缩
        self.splitter.setStretchFactor(0, 0)
        self.lineEdit_3 = QtWidgets.QLineEdit(self.splitter)
        self.lineEdit_3.setObjectName("lineEdit_3")
         # 将 lineEdit_3 添加到 splitter
        self.splitter.addWidget(self.lineEdit_3)

        # 设置伸缩因子，lineEdit_3 索引为 1，可伸缩
        self.splitter.setStretchFactor(1, 1)
        self.splitter_2 = QtWidgets.QSplitter(self.splitter)
        self.splitter_2.setOrientation(QtCore.Qt.Horizontal)
        self.splitter_2.setObjectName("splitter_2")
        # self.label_6 = QtWidgets.QLabel(self.splitter_2)
        # self.label_6.setObjectName("label_6")
        # self.lineEdit_4 = QtWidgets.QLineEdit(self.splitter_2)
        # self.lineEdit_4.setMaximumSize(QtCore.QSize(200, 16777215))
        # self.lineEdit_4.setObjectName("lineEdit_4")
        self.splitter_3 = QtWidgets.QSplitter(self.splitter)
        self.splitter_3.setOrientation(QtCore.Qt.Horizontal)
        self.splitter_3.setObjectName("splitter_3")
        self.label_8 = QtWidgets.QLabel(self.splitter_3)
        self.label_8.setObjectName("label_8")
        self.comboBox_3 = QtWidgets.QComboBox(self.splitter_3)
        self.comboBox_3.setMinimumSize(QtCore.QSize(200, 0))
        self.comboBox_3.setObjectName("comboBox_3")
        custom_list_view = CustomListView()
        self.comboBox_3.setView(custom_list_view)
        # self.comboBox_3.addItem("")
        # self.comboBox_3.addItem("")
        self.pushButton = QtWidgets.QPushButton(self.splitter)
        self.pushButton.setObjectName("pushButton")
        self.horizontalLayout.addWidget(self.splitter)
        self.verticalLayout_3.addLayout(self.horizontalLayout)
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.label_4 = QtWidgets.QLabel(self.horizontalLayoutWidget_2)
        self.label_4.setObjectName("label_4")
        self.horizontalLayout_3.addWidget(self.label_4)
        self.lineEdit_2 = QtWidgets.QLineEdit(self.horizontalLayoutWidget_2)
        self.lineEdit_2.setObjectName("lineEdit_2")
        self.horizontalLayout_3.addWidget(self.lineEdit_2)
        self.horizontalLayout_4 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_4.setObjectName("horizontalLayout_4")
        self.verticalLayout_3.addLayout(self.horizontalLayout_4)
        self.verticalLayout_3.addLayout(self.horizontalLayout_3)
        self.label_3 = QtWidgets.QLabel(self.horizontalLayoutWidget_2)
        self.label_3.setMinimumSize(QtCore.QSize(0, 40))
        self.label_3.setAlignment(QtCore.Qt.AlignCenter)
        self.label_3.setObjectName("label_3")
        self.verticalLayout_3.addWidget(self.label_3)
        self.textBrowser = QtWidgets.QTextBrowser(self.horizontalLayoutWidget_2)
        self.textBrowser.setObjectName("textBrowser")
        self.verticalLayout_3.addWidget(self.textBrowser)
        self.label_7 = QtWidgets.QLabel(self.horizontalLayoutWidget_2)
        self.label_7.setMinimumSize(QtCore.QSize(0, 40))
        self.label_7.setAlignment(QtCore.Qt.AlignCenter)
        self.label_7.setObjectName("label_7")
        self.verticalLayout_3.addWidget(self.label_7)
        self.textBrowser_2 = QtWidgets.QTextBrowser(self.horizontalLayoutWidget_2)
        self.textBrowser_2.setObjectName("textBrowser_2")
        self.verticalLayout_3.addWidget(self.textBrowser_2)
        
        self.horizontalLayout_2.addLayout(self.verticalLayout_3)
        self.horizontalLayout_2.setStretch(1, 5)
        self.tabWidget.addTab(self.tab, "")

        self.tab_3 = QtWidgets.QWidget()
        self.tab_3.setObjectName("tab_3")
        self.verticalLayout_4 = QtWidgets.QVBoxLayout(self.tab_3)
        self.verticalLayout_4.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_4.setSpacing(10)  # 设置布局内控件间距
        self.verticalLayout_4.setObjectName("verticalLayout_4")
        self.horizontalLayout_6 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_6.setObjectName("horizontalLayout_6")
        self.splitter_5 = QtWidgets.QSplitter(QtCore.Qt.Horizontal)
        self.splitter_5.setObjectName("splitter_5")
        self.comboBox_4 = QtWidgets.QComboBox(self.splitter_5)
        self.comboBox_4.setMinimumSize(QtCore.QSize(200, 0))
        self.comboBox_4.setObjectName("comboBox_4")
        self.comboBox_4.addItem("")
        self.comboBox_4.addItem("")
        self.comboBox_4.addItem("")
        self.splitter_4 = QtWidgets.QSplitter(self.splitter_5)
        self.splitter_4.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.splitter_4.setOrientation(QtCore.Qt.Horizontal)
        self.splitter_4.setObjectName("splitter_4")
        self.lineEdit = QtWidgets.QLineEdit(self.splitter_4)
        self.lineEdit.setEnabled(True)
        self.lineEdit.setMinimumSize(QtCore.QSize(100, 30))
        self.lineEdit.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.lineEdit.setObjectName("lineEdit")
        self.horizontalLayout_6.addWidget(self.splitter_5)
        self.pushButton_6 = QtWidgets.QPushButton(self.splitter_5)
        self.pushButton_6.setObjectName("pushButton_6")
        self.horizontalLayout_6.addWidget(self.pushButton_6)
        self.pushButton_5 = QtWidgets.QPushButton(self.splitter_5)
        self.pushButton_5.setObjectName("pushButton_5")
        self.horizontalLayout_6.addWidget(self.pushButton_5)
        self.pushButton_8 = QtWidgets.QPushButton(self.splitter_5)
        self.pushButton_8.setObjectName("pushButton_8")
        self.horizontalLayout_6.addWidget(self.pushButton_8)
        self.pushButton_7 = QtWidgets.QPushButton(self.splitter_5)
        self.pushButton_7.setObjectName("pushButton_7")
        self.horizontalLayout_6.addWidget(self.pushButton_7)
        self.verticalLayout_4.addLayout(self.horizontalLayout_6)
        self.tableWidget_3 = QtWidgets.QTableWidget(self.splitter_4)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.tableWidget_3.sizePolicy().hasHeightForWidth())
        self.tableWidget_3.setSizePolicy(sizePolicy)
        self.tableWidget_3.setObjectName("tableWidget_3")
        self.tableWidget_3.setColumnCount(6)
        self.tableWidget_3.setRowCount(0)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_3.setHorizontalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_3.setHorizontalHeaderItem(1, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_3.setHorizontalHeaderItem(2, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_3.setHorizontalHeaderItem(3, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_3.setHorizontalHeaderItem(4, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_3.setHorizontalHeaderItem(5, item)

        # 获取水平表头
        header = self.tableWidget_3.horizontalHeader()
        # 设置最后一列自动拉伸，其余列可手动调整
        for col in range(self.tableWidget_3.columnCount() - 1):
            header.setSectionResizeMode(col, QtWidgets.QHeaderView.Interactive)
        header.setSectionResizeMode(self.tableWidget_3.columnCount() - 1, QtWidgets.QHeaderView.Stretch)

        # 设置垂直表头自动拉伸（可选）
        vertical_header = self.tableWidget_3.verticalHeader()
        vertical_header.setSectionResizeMode(QtWidgets.QHeaderView.Stretch)
        self.verticalLayout_4.addWidget(self.tableWidget_3)
        self.tabWidget.addTab(self.tab_3, "")

        self.tab_2 = QtWidgets.QWidget()
        self.tab_2.setObjectName("tab_2")
        # 使用垂直布局，与 tab_3 一致
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(self.tab_2)
        self.verticalLayout_2.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_2.setSpacing(10)  # 设置布局内控件间距，与 tab_3 一致
        self.verticalLayout_2.setObjectName("verticalLayout_2")

        # 创建类似 tab_3 的水平布局，用于放置按钮和其他控件
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")

        # 这里可以添加类似 tab_3 的 QComboBox、QLineEdit 等控件，暂时用占位标签代替
        # self.label_placeholder = QtWidgets.QLabel("日志管理操作控件占位", self.tab_2)
        # self.horizontalLayout_2.addWidget(self.label_placeholder)

        self.pushButton_4 = QtWidgets.QPushButton("导出日志", self.tab_2)
        self.pushButton_4.setObjectName("pushButton_4")
        self.horizontalLayout_2.addWidget(self.pushButton_4)

        self.verticalLayout_2.addLayout(self.horizontalLayout_2)

        self.tableWidget = QtWidgets.QTableWidget(self.tab_2)
        # 设置尺寸策略，与 tableWidget_3 一致
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.tableWidget.sizePolicy().hasHeightForWidth())
        self.tableWidget.setSizePolicy(sizePolicy)
        self.tableWidget.setObjectName("tableWidget")
        self.tableWidget.setColumnCount(4)
        self.tableWidget.setRowCount(0)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(1, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(2, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(3, item)

        # 获取水平表头
        header = self.tableWidget.horizontalHeader()
        # 设置最后一列自动拉伸，其余列可手动调整，与 tableWidget_3 一致
        for col in range(self.tableWidget.columnCount() - 1):
            header.setSectionResizeMode(col, QtWidgets.QHeaderView.Interactive)
        header.setSectionResizeMode(self.tableWidget.columnCount() - 1, QtWidgets.QHeaderView.Stretch)

        # 设置垂直表头自动拉伸（可选），与 tableWidget_3 一致
        vertical_header = self.tableWidget.verticalHeader()
        vertical_header.setSectionResizeMode(QtWidgets.QHeaderView.Stretch)
        self.verticalLayout_2.addWidget(self.tableWidget)

        self.tabWidget.addTab(self.tab_2, "")

        #代码审计窗口
        self.tab_4 = QtWidgets.QWidget()
        self.tab_4.setObjectName("tab_4")
        self.tabWidget_2 = QtWidgets.QTabWidget(self.tab_4)
        self.tabWidget_2.setGeometry(QtCore.QRect(10, 20, 731, 501))
        self.tabWidget_2.setObjectName("tabWidget_2")
        #GPT代码审计
        self.tab_5 = QtWidgets.QWidget()
        self.tab_5.setObjectName("tab_5")
        # Create the main vertical layout
        main_vertical_layout = QtWidgets.QVBoxLayout(self.tab_5)
        main_vertical_layout.setContentsMargins(10, 10, 10, 10)
        main_vertical_layout.setSpacing(10)

        # Create the input controls horizontal layout
        input_horizontal_layout = QtWidgets.QHBoxLayout()
        input_horizontal_layout.setSpacing(10)

        self.label_70 = QtWidgets.QLabel("Code Path:", self.tab_5)
        self.label_70.setObjectName("label_70")
        input_horizontal_layout.addWidget(self.label_70)

        self.lineEdit_windows_ip = QtWidgets.QLineEdit(self.tab_5)
        self.lineEdit_windows_ip.setObjectName("lineEdit_windows_ip")
        input_horizontal_layout.addWidget(self.lineEdit_windows_ip)

        self.label_71 = QtWidgets.QLabel("OpenAI API Key:", self.tab_5)
        self.label_71.setObjectName("label_71")
        input_horizontal_layout.addWidget(self.label_71)

        self.lineEdit_windows_port = QtWidgets.QLineEdit(self.tab_5)
        self.lineEdit_windows_port.setObjectName("lineEdit_windows_port")
        input_horizontal_layout.addWidget(self.lineEdit_windows_port)

        self.pushButton_windows_exe = QtWidgets.QPushButton("Execute Command", self.tab_5)
        self.pushButton_windows_exe.setObjectName("pushButton_windows_exe")
        input_horizontal_layout.addWidget(self.pushButton_windows_exe)

        # Add the input controls horizontal layout to the main vertical layout
        main_vertical_layout.addLayout(input_horizontal_layout)

        self.plainTextEdit_windows_result = QtWidgets.QPlainTextEdit(self.tab_5)
        self.plainTextEdit_windows_result.setReadOnly(True)
        self.plainTextEdit_windows_result.setPlainText("")
        self.plainTextEdit_windows_result.setObjectName("plainTextEdit_windows_result")
        main_vertical_layout.addWidget(self.plainTextEdit_windows_result)
        #self.tabWidget_2.addTab(self.tab_5, "")
        #全局搜索关键字
        self.tab_6 = QtWidgets.QWidget()
        self.tab_6.setObjectName("tab_6")
        # 创建主垂直布局
        main_vertical_layout = QtWidgets.QVBoxLayout(self.tab_6)
        main_vertical_layout.setContentsMargins(10, 10, 10, 10)
        main_vertical_layout.setSpacing(10)

        # 创建输入控件水平布局
        input_horizontal_layout = QtWidgets.QHBoxLayout()
        input_horizontal_layout.setSpacing(10)

        self.label_2 = QtWidgets.QLabel("代码路径", self.tab_6)
        self.label_2.setObjectName("label_2")
        input_horizontal_layout.addWidget(self.label_2)

        self.lineEdit_windows_ip_2 = QtWidgets.QLineEdit(self.tab_6)
        self.lineEdit_windows_ip_2.setObjectName("lineEdit_windows_ip_2")
        input_horizontal_layout.addWidget(self.lineEdit_windows_ip_2)

        # 新增选择文件夹按钮
        self.pushButton_select_folder = QtWidgets.QPushButton("选择文件夹", self.tab_6)
        self.pushButton_select_folder.setObjectName("pushButton_select_folder")
        input_horizontal_layout.addWidget(self.pushButton_select_folder)

        self.label_3 = QtWidgets.QLabel("命令", self.tab_6)
        self.label_3.setObjectName("label_3")
        input_horizontal_layout.addWidget(self.label_3)

        self.lineEdit_windows_ip_3 = QtWidgets.QLineEdit(self.tab_6)
        self.lineEdit_windows_ip_3.setObjectName("lineEdit_windows_ip_3")
        input_horizontal_layout.addWidget(self.lineEdit_windows_ip_3)

        # 将输入控件水平布局添加到主垂直布局
        main_vertical_layout.addLayout(input_horizontal_layout)

        self.pushButton_weblogic_uploadshell = QtWidgets.QPushButton("执行命令", self.tab_6)
        self.pushButton_weblogic_uploadshell.setObjectName("pushButton_weblogic_uploadshell")
        input_horizontal_layout.addWidget(self.pushButton_weblogic_uploadshell)  # 将按钮添加到水平布局

        self.plainTextEdit_weblogic_result = QtWidgets.QPlainTextEdit(self.tab_6)
        self.plainTextEdit_weblogic_result.setReadOnly(True)
        self.plainTextEdit_weblogic_result.setObjectName("plainTextEdit_weblogic_result")
        main_vertical_layout.addWidget(self.plainTextEdit_weblogic_result)
        self.tabWidget_2.addTab(self.tab_6, "")
        # 危险函数搜索
        self.tab_9 = QtWidgets.QWidget()
        self.tab_9.setObjectName("tab_9")

        # 创建垂直布局
        vertical_layout = QtWidgets.QVBoxLayout(self.tab_9)

        # 创建水平布局用于放置输入控件
        input_horizontal_layout = QtWidgets.QHBoxLayout()

        self.label_72 = QtWidgets.QLabel(self.tab_9)
        self.label_72.setObjectName("label_72")
        input_horizontal_layout.addWidget(self.label_72)

        # 创建一个新的水平布局用于 QLineEdit 和 QPushButton
        line_edit_layout = QtWidgets.QHBoxLayout()

        self.lineEdit_windows_ip_4 = QtWidgets.QLineEdit(self.tab_9)
        self.lineEdit_windows_ip_4.setObjectName("lineEdit_windows_ip_4")
        input_horizontal_layout.addWidget(self.lineEdit_windows_ip_4)
        
        self.pushButton_select_file = QtWidgets.QPushButton("选择文件", self.tab_9)
        self.pushButton_select_file.setObjectName("pushButton_select_file")
        line_edit_layout.addWidget(self.pushButton_select_file)

        # 将包含 QLineEdit 和 QPushButton 的布局添加到输入水平布局
        input_horizontal_layout.addLayout(line_edit_layout)

        self.comboBox_6 = QtWidgets.QComboBox(self.tab_9)
        self.comboBox_6.setObjectName("comboBox_6")
        input_horizontal_layout.addWidget(self.comboBox_6)

        self.pushButton_weblogic_uploadshell_2 = QtWidgets.QPushButton(self.tab_9)
        self.pushButton_weblogic_uploadshell_2.setObjectName("pushButton_weblogic_uploadshell_2")
        input_horizontal_layout.addWidget(self.pushButton_weblogic_uploadshell_2)

        # 将水平布局添加到垂直布局
        vertical_layout.addLayout(input_horizontal_layout)

        self.plainTextEdit_weblogic_result_2 = QtWidgets.QPlainTextEdit(self.tab_9)
        self.plainTextEdit_weblogic_result_2.setReadOnly(True)
        self.plainTextEdit_weblogic_result_2.setObjectName("plainTextEdit_weblogic_result_2")
        vertical_layout.addWidget(self.plainTextEdit_weblogic_result_2)

        self.tabWidget_2.addTab(self.tab_9, "")
        #自动审计
        self.tab_auto_audit = QtWidgets.QWidget()
        self.tab_auto_audit.setObjectName("tab_auto_audit")
        # 创建主垂直布局
        main_vertical_layout = QtWidgets.QVBoxLayout(self.tab_auto_audit)
        main_vertical_layout.setContentsMargins(10, 10, 10, 10)
        main_vertical_layout.setSpacing(10)

        # 创建水平布局用于放置按钮
        button_horizontal_layout = QtWidgets.QHBoxLayout()
        button_horizontal_layout.setSpacing(10)

        self.label_auto_audit_path = QtWidgets.QLabel(self.tab_auto_audit)
        self.label_auto_audit_path.setText("源码路径:")
        button_horizontal_layout.addWidget(self.label_auto_audit_path)

        self.lineEdit_auto_audit_path = QtWidgets.QLineEdit(self.tab_auto_audit)
        button_horizontal_layout.addWidget(self.lineEdit_auto_audit_path)

        self.comboBox_language = QtWidgets.QComboBox(self.tab_auto_audit)
        # self.comboBox_language.addItems(["PHP", "Java"])
        button_horizontal_layout.addWidget(self.comboBox_language)

        self.pushButton_import_yaml = QtWidgets.QPushButton(self.tab_auto_audit)
        self.pushButton_import_yaml.setText("导入YAML规则")
        button_horizontal_layout.addWidget(self.pushButton_import_yaml)

        self.pushButton_run_scan = QtWidgets.QPushButton(self.tab_auto_audit)
        self.pushButton_run_scan.setText("导入源码并扫描")
        button_horizontal_layout.addWidget(self.pushButton_run_scan)

        # 将按钮水平布局添加到主垂直布局
        main_vertical_layout.addLayout(button_horizontal_layout)

        # self.plainTextEdit_auto_audit_result = QtWidgets.QPlainTextEdit(self.tab_auto_audit)
        # self.plainTextEdit_auto_audit_result.setReadOnly(True)
        # self.plainTextEdit_auto_audit_result.setPlainText("")
        # self.plainTextEdit_auto_audit_result.setObjectName("plainTextEdit_auto_audit_result")
        # main_vertical_layout.addWidget(self.plainTextEdit_auto_audit_result)

        self.listWidget_2 = QtWidgets.QListWidget(self.tab_auto_audit)
        self.listWidget_2.setObjectName("listWidget_2")
        main_vertical_layout.addWidget(self.listWidget_2)
        self.tabWidget_2.addTab(self.tab_auto_audit, "")
        self.tabWidget.addTab(self.tab_4, "")

        # ============== 添加tab_7 ==============
        self.tab_7 = QtWidgets.QWidget()
        self.tab_7.setObjectName("tab_7")
        
        # tab_7布局（水平分割）
        tab7_layout = QtWidgets.QHBoxLayout(self.tab_7)
        tab7_layout.setContentsMargins(0, 0, 0, 0)
        
        # 左侧工具盒
        self.tool_box = QtWidgets.QToolBox()
        self.tool_box.setMinimumWidth(200)
        
        # 添加SQL工具页
        # sql_tools = QtWidgets.QWidget()
        # sql_layout = QtWidgets.QVBoxLayout(sql_tools)
        # self.sql_list = QtWidgets.QListWidget()
        # self.sql_list.addItems(['sqlmap', 'SQLExploit', 'NoSQLMap'])
        # sql_layout.addWidget(self.sql_list)

        # self.tool_box.addItem(sql_tools, "SQL利用工具")
        
        # 右侧操作面板
        right_panel = QtWidgets.QWidget()
        right_layout = QtWidgets.QVBoxLayout(right_panel)
        
        # 命令输入区
        cmd_group = QtWidgets.QGroupBox("命令执行")
        cmd_layout = QtWidgets.QVBoxLayout(cmd_group)
        self.cmd_input = QtWidgets.QLineEdit()
        self.cmd_input.setPlaceholderText("输入完整命令（示例：sqlmap -u http://target.com --batch）")
        self.run_btn = QtWidgets.QPushButton("执行")
        cmd_layout.addWidget(self.cmd_input)
        cmd_layout.addWidget(self.run_btn)
        
        # 结果展示区
        result_group = QtWidgets.QGroupBox("执行结果")
        result_layout = QtWidgets.QVBoxLayout(result_group)
        # self.result_output = QtWidgets.QTextEdit()
        # self.result_output.setReadOnly(True)
        self.terminal = CommandTerminal()
        result_layout.addWidget(self.terminal)
        
        # 组装右侧面板
        right_layout.addWidget(cmd_group)
        right_layout.addWidget(result_group)
        right_layout.setStretch(1, 3)  # 结果区占3/4高度
        
        # 将左右部分添加到tab7
        tab7_layout.addWidget(self.tool_box)
        tab7_layout.addWidget(right_panel)
        tab7_layout.setStretch(1, 5)  # 右侧占5/6宽度
        
        # 将tab_7添加到主TabWidget
        self.tabWidget.addTab(self.tab_7, "外部工具")

        # ============== 添加tab_8 ==============
        self.tab_8 = QtWidgets.QWidget()
        self.tab_8.setObjectName("tab_8")
        # self.verticalLayoutWidget_3 = QtWidgets.QWidget(self.tab_8)
        # self.verticalLayoutWidget_3.setGeometry(QtCore.QRect(20, 30, 926, 561))
        # self.verticalLayoutWidget_3.setObjectName("verticalLayoutWidget_3")
        # self.verticalLayout_5 = QtWidgets.QVBoxLayout(self.verticalLayoutWidget_3)
        # self.verticalLayout_5.setContentsMargins(0, 0, 0, 0)
        # self.verticalLayout_5.setObjectName("verticalLayout_5")
        self.verticalLayout_5 = QtWidgets.QVBoxLayout(self.tab_8)
        self.verticalLayout_5.setContentsMargins(0, 0, 0, 0)  # 设置整体边距
        self.verticalLayout_5.setSpacing(10)  # 设置布局内控件间距
        self.horizontalLayout_7 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_7.setObjectName("horizontalLayout_7")
        self.splitter_6 = QtWidgets.QSplitter(QtCore.Qt.Horizontal)
        #self.splitter_6.setOrientation(QtCore.Qt.Horizontal)
        self.splitter_6.setObjectName("splitter_6")
        self.comboBox_5 = QtWidgets.QComboBox(self.splitter_6)
        self.comboBox_5.setMinimumSize(QtCore.QSize(200, 0))
        self.comboBox_5.setObjectName("comboBox_5")
        self.comboBox_5.addItem("")
        self.comboBox_5.addItem("")
        self.splitter_7 = QtWidgets.QSplitter(self.splitter_6)
        self.splitter_7.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.splitter_7.setOrientation(QtCore.Qt.Horizontal)
        self.splitter_7.setObjectName("splitter_7")
        self.lineEdit_5 = QtWidgets.QLineEdit(self.splitter_7)
        self.lineEdit_5.setEnabled(True)
        self.lineEdit_5.setMinimumSize(QtCore.QSize(100, 30))
        self.lineEdit_5.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.lineEdit_5.setObjectName("lineEdit_5")
        self.horizontalLayout_7.addWidget(self.splitter_6)
        self.pushButton_9 = QtWidgets.QPushButton(self.splitter_6)
        self.pushButton_9.setObjectName("pushButton_9")
        self.horizontalLayout_7.addWidget(self.pushButton_9)
        self.pushButton_10 = QtWidgets.QPushButton(self.splitter_6)
        self.pushButton_10.setObjectName("pushButton_10")
        self.horizontalLayout_7.addWidget(self.pushButton_10)
        self.pushButton_11 = QtWidgets.QPushButton(self.splitter_6)
        self.pushButton_11.setObjectName("pushButton_11")
        self.horizontalLayout_7.addWidget(self.pushButton_11)
        self.pushButton_12 = QtWidgets.QPushButton(self.splitter_6)
        self.pushButton_12.setObjectName("pushButton_12")
        self.horizontalLayout_7.addWidget(self.pushButton_12)
        self.verticalLayout_5.addLayout(self.horizontalLayout_7)
        self.tableWidget_4 = QtWidgets.QTableWidget(self.splitter_7)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.tableWidget_4.sizePolicy().hasHeightForWidth())
        self.tableWidget_4.setSizePolicy(sizePolicy)
        self.tableWidget_4.setObjectName("tableWidget_4")
        self.tableWidget_4.setColumnCount(5)
        self.tableWidget_4.setRowCount(0)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_4.setHorizontalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_4.setHorizontalHeaderItem(1, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_4.setHorizontalHeaderItem(2, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_4.setHorizontalHeaderItem(3, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_4.setHorizontalHeaderItem(4, item)
        # 获取水平表头
        header = self.tableWidget_4.horizontalHeader()
        # 设置最后一列自动拉伸，其余列可手动调整
        for col in range(self.tableWidget_4.columnCount() - 1):
            header.setSectionResizeMode(col, QtWidgets.QHeaderView.Interactive)
        header.setSectionResizeMode(self.tableWidget_4.columnCount() - 1, QtWidgets.QHeaderView.Stretch)

        # 设置垂直表头自动拉伸（可选）
        vertical_header = self.tableWidget_4.verticalHeader()
        vertical_header.setSectionResizeMode(QtWidgets.QHeaderView.Stretch)
       
        self.verticalLayout_5.addWidget(self.tableWidget_4)
        self.tabWidget.addTab(self.tab_8, "")


        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 920, 26))
        self.menubar.setObjectName("menubar")
        self.menu = QtWidgets.QMenu(self.menubar)
        self.menu.setObjectName("menu")
        self.menu_2 = QtWidgets.QMenu(self.menubar)
        self.menu_2.setObjectName("menu_2")
        # self.menu_3 = QtWidgets.QMenu(self.menubar)
        # self.menu_3.setObjectName("menu_3")
        # self.menu_4 = QtWidgets.QMenu(self.menubar)
        # self.menu_4.setObjectName("menu_4")
        
        self.action1 = QtWidgets.QAction(MainWindow)
        self.action1.setObjectName("action1")
        self.action2 = QtWidgets.QAction(MainWindow)
        self.action2.setObjectName("action2")
        # 创建 QAction 对象
        # self.action_new_project = QtWidgets.QAction(MainWindow)
        # self.action_new_project.setObjectName("action_new_project")
        # self.action_open_file = QtWidgets.QAction(MainWindow)
        # self.action_open_file.setObjectName("action_open_file")
        self.action_exit = QtWidgets.QAction(MainWindow)
        self.action_exit.setObjectName("action_exit")
        # 将 QAction 添加到 menu
        # self.menu.addAction(self.action_new_project)
        # self.menu.addAction(self.action_open_file)
        self.menu.addSeparator()  # 添加分隔线
        self.menu.addAction(self.action_exit)

        self.menu_2.addAction(self.action1)
        self.menu_2.addAction(self.action2)
        self.menu_2.addSeparator()
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)
        self.menubar.addAction(self.menu.menuAction())
        self.menubar.addAction(self.menu_2.menuAction())
        # self.menubar.addAction(self.menu_3.menuAction())
        # self.menubar.addAction(self.menu_4.menuAction())
        
        

        self.retranslateUi(MainWindow)
        self.tabWidget.setCurrentIndex(0)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "Web常见漏洞验证工具"))
        __sortingEnabled = self.listWidget.isSortingEnabled()
        self.listWidget.setSortingEnabled(False)
        # item = self.listWidget.item(0)
        # item.setText(_translate("MainWindow", "新建项目"))
        # item = self.listWidget.item(1)
        # item.setText(_translate("MainWindow", "新建项目"))
        # item = self.listWidget.item(2)
        # item.setText(_translate("MainWindow", "新建项目"))
        # item = self.listWidget.item(3)
        # item.setText(_translate("MainWindow", "新建项目"))
        # item = self.listWidget.item(4)
        # item.setText(_translate("MainWindow", "新建项目"))
        # item = self.listWidget.item(5)
        # item.setText(_translate("MainWindow", "新建项目"))
        self.listWidget.setSortingEnabled(__sortingEnabled)
        self.label_5.setText(_translate("MainWindow", "目标url : "))
        # self.label_6.setText(_translate("MainWindow", "目标url : "))
        self.label_8.setText(_translate("MainWindow", "漏洞 : "))
        self.label_6.setText(_translate("MainWindow", "批量扫描url : "))
        self.pushButton_2.setText(_translate("MainWindow", "选择文件"))
        self.pushButton_3.setText(_translate("MainWindow", "开始运行"))
        # self.comboBox_3.setItemText(0, _translate("MainWindow", "蓝凌OA SQL注入漏洞"))
        # self.comboBox_3.setItemText(1, _translate("MainWindow", "新建项目"))
        self.pushButton.setText(_translate("MainWindow", "开始运行"))
        self.label_4.setText(_translate("MainWindow", "命令演示 : "))
        self.label_3.setText(_translate("MainWindow", "命令提示"))
        self.label_7.setText(_translate("MainWindow", "执行结果"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab), _translate("MainWindow", "漏洞验证"))
        self.comboBox_4.setItemText(0, _translate("MainWindow", "根据所属分类查询"))
        self.comboBox_4.setItemText(1, _translate("MainWindow", "根据所属应用查询"))
        self.comboBox_4.setItemText(2, _translate("MainWindow", "根据漏洞名称查询"))
        self.pushButton_6.setText(_translate("MainWindow", "查询"))
        self.pushButton_5.setText(_translate("MainWindow", "添加"))
        self.pushButton_8.setText(_translate("MainWindow", "修改"))
        self.pushButton_7.setText(_translate("MainWindow", "删除"))
        item = self.tableWidget_3.horizontalHeaderItem(0)
        item.setText(_translate("MainWindow", "所属分类"))
        item = self.tableWidget_3.horizontalHeaderItem(1)
        item.setText(_translate("MainWindow", "所属应用"))
        item = self.tableWidget_3.horizontalHeaderItem(2)
        item.setText(_translate("MainWindow", "漏洞名称"))
        item = self.tableWidget_3.horizontalHeaderItem(3)
        item.setText(_translate("MainWindow", "存储位置"))
        item = self.tableWidget_3.horizontalHeaderItem(4)
        item.setText(_translate("MainWindow", "危险程度"))
        item = self.tableWidget_3.horizontalHeaderItem(5)
        item.setText(_translate("MainWindow", "修复建议"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_3), _translate("MainWindow", "pyload管理"))
        item = self.tableWidget.horizontalHeaderItem(0)
        item.setText(_translate("MainWindow", "执行时间"))
        item = self.tableWidget.horizontalHeaderItem(1)
        item.setText(_translate("MainWindow", "所属模块"))
        item = self.tableWidget.horizontalHeaderItem(2)
        item.setText(_translate("MainWindow", "操作"))
        item = self.tableWidget.horizontalHeaderItem(3)
        item.setText(_translate("MainWindow", "执行结果"))
        self.pushButton_4.setText(_translate("MainWindow", "导出日志"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_2), _translate("MainWindow", "日志管理"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_4), _translate("MainWindow", "代码审计"))
        self.label_70.setText(_translate("MainWindow", "代码路径:"))
        self.label_71.setText(_translate("MainWindow", "OpenAI API 密钥"))
        self.pushButton_windows_exe.setText(_translate("MainWindow", "执行命令"))
        self.tabWidget_2.setTabText(self.tabWidget_2.indexOf(self.tab_5), _translate("MainWindow", "GPT代码审计"))
        self.plainTextEdit_weblogic_result.setPlainText(_translate("MainWindow", "支持：Java ，PHP，asp，aspx，jsp，jspx，python，go，全局搜索关键字。"))
        self.pushButton_weblogic_uploadshell.setText(_translate("MainWindow", "执行命令"))
        self.label_2.setText(_translate("MainWindow", "代码路径"))
        self.label_3.setText(_translate("MainWindow", "关键词"))
        self.tabWidget_2.setTabText(self.tabWidget_2.indexOf(self.tab_6), _translate("MainWindow", "全局搜索关键字"))
        self.plainTextEdit_weblogic_result_2.setPlainText(_translate("MainWindow", "危险函数"))
        self.label_72.setText(_translate("MainWindow", "危险函数搜索"))
        self.pushButton_weblogic_uploadshell_2.setText(_translate("MainWindow", "搜索命令"))
        self.tabWidget_2.setTabText(self.tabWidget_2.indexOf(self.tab_9), _translate("MainWindow", "危险函数搜索"))
        self.tabWidget_2.setTabText(self.tabWidget_2.indexOf(self.tab_auto_audit), _translate("MainWindow", "自动化代码审计"))
        self.comboBox_5.setItemText(0, _translate("MainWindow", "根据工具名称查询"))
        self.comboBox_5.setItemText(1, _translate("MainWindow", "根据工具分类查询"))
        self.pushButton_9.setText(_translate("MainWindow", "查询"))
        self.pushButton_10.setText(_translate("MainWindow", "添加"))
        self.pushButton_11.setText(_translate("MainWindow", "修改"))
        self.pushButton_12.setText(_translate("MainWindow", "删除"))
        item = self.tableWidget_4.horizontalHeaderItem(0)
        item.setText(_translate("MainWindow", "所属分类"))
        item = self.tableWidget_4.horizontalHeaderItem(1)
        item.setText(_translate("MainWindow", "工具名称"))
        item = self.tableWidget_4.horizontalHeaderItem(2)
        item.setText(_translate("MainWindow", "存储位置"))
        item = self.tableWidget_4.horizontalHeaderItem(3)
        item.setText(_translate("MainWindow", "执行工具命令"))
        item = self.tableWidget_4.horizontalHeaderItem(4)
        item.setText(_translate("MainWindow", "说明"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_8), _translate("MainWindow", "外部工具管理"))
        self.menu.setTitle(_translate("MainWindow", "菜单"))
        self.action_exit.setText(_translate("MainWindow", "退出"))
        self.menu_2.setTitle(_translate("MainWindow", "代理"))
        # self.menu_3.setTitle(_translate("MainWindow", "设置"))
        # self.menu_4.setTitle(_translate("MainWindow", "关于"))
        self.action1.setText(_translate("MainWindow", "代理设置"))
        self.action2.setText(_translate("MainWindow", "关闭代理"))

    
